/*
 * Sample project for KubeQuest
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package projectserver

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name                string
	Method              string
	Pattern             string
	HandlerFunc         http.HandlerFunc
	RequiredPermissions []string
}

type Routes []Route

func renderIndexPage(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "text/html")
	w.Write([]byte(html))
}

// func renderIndexPage(w http.ResponseWriter, r *http.Request) {
// 	log.Println("Current working directory:", http.Dir("."))

// 	tmpl := template.Must(template.ParseFiles("/app/web/index.html"))
// 	if err := tmpl.Execute(w, nil); err != nil {
// 		log.Printf("Error rendering template: %v", err)
// 		http.Error(w, "Error rendering template", http.StatusInternalServerError)
// 	}
// }

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true).UseEncodedPath()

	router.HandleFunc("/", renderIndexPage).Methods("GET")
	http.Handle("/static/", http.StripPrefix("/static/", http.FileServer(http.Dir("/root/web"))))

	router.HandleFunc("/ws", WebSocketHandler).Methods("GET")

	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)
		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
		continue
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	fmt.Fprintf(w, "{\"name\": \"Sample project for KubeQuest\",\"version\": \"1.0.0\"}")
	w.WriteHeader(http.StatusOK)
}

func Healthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/api/",
		Index,
		[]string{},
	},

	Route{
		"Healthz",
		"GET",
		"/healthz",
		Healthz,
		[]string{},
	},

	Route{
		"GetLike",
		strings.ToUpper("Get"),
		"/api/like",
		GetLike,
		[]string{},
	},

	Route{
		"PostLike",
		strings.ToUpper("Post"),
		"/api/like",
		PostLike,
		[]string{},
	},

	Route{
		"ResetCounter",
		strings.ToUpper("Delete"),
		"/api/reset",
		ResetCounter,
		[]string{},
	},
}

const html string = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Like Animal</title>
    <style>
        body {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
        }
        .container {
            display: flex;
            justify-content: space-around;
            width: 100%;
            max-width: 600px;
            margin-bottom: 20px;
        }
        .counter {
            display: flex;
            flex-direction: column;
            align-items: center;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .counter h3 {
            margin: 0;
            font-size: 24px;
            color: #333;
        }
        .counter p {
            font-size: 24px;
            margin: 10px 0;
            color: #666;
        }
        .counter button {
            padding: 10px 20px;
            font-size: 16px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        .counter button:hover {
            background-color: #0056b3;
        }
        #resetButton {
            padding: 10px 20px;
            font-size: 16px;
            background-color: #dc3545;
            color: #fff;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        #resetButton:hover {
            background-color: #c82333;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="counter">
            <h3>Dog</h3>
            <p><span id="dogCount">0</span></p>
            <form id="dogForm">
                <input type="hidden" id="animalDog" name="animal" value="dog">
                <button type="submit">Like Dog</button>
            </form>
        </div>
        <div class="counter">
            <h3>Cat</h3>
            <p><span id="catCount">0</span></p>
            <form id="catForm">
                <input type="hidden" id="animalCat" name="animal" value="cat">
                <button type="submit">Like Cat</button>
            </form>
        </div>
    </div>
    <button id="resetButton">Reset Counts</button>

    <script>
        const protocol = window.location.protocol === "https:" ? "wss" : "ws";
        const socket = new WebSocket(protocol + "://" + window.location.host + "/ws");

        socket.onmessage = function(event) {
            const data = JSON.parse(event.data);
            document.getElementById('dogCount').textContent = data.dog;
            document.getElementById('catCount').textContent = data.cat;
        };
        
        socket.onerror = function(error) {
            console.error('WebSocket error:', error);
        };
        
        socket.onclose = function() {
            console.warn('WebSocket closed. Attempting to reconnect...');
            setTimeout(() => {
                connectWebSocket();
            }, 5000);
        };

        function connectWebSocket() {
            socket.onmessage = function(event) {
                const data = JSON.parse(event.data);
                document.getElementById('dogCount').textContent = data.dog;
                document.getElementById('catCount').textContent = data.cat;
            };
            socket.onerror = function(error) {
                console.error('WebSocket error:', error);
            };
            socket.onclose = function() {
                console.warn('WebSocket closed. Attempting to reconnect...');
                setTimeout(connectWebSocket, 5000);
            };
        }
        connectWebSocket();

        document.addEventListener('DOMContentLoaded', function() {
            function updateLikeCounts() {
                fetch('/api/like', {
                    method: 'GET'
                })
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }
                    return response.json();
                })
                .then(data => {
                    document.getElementById('dogCount').textContent = data.dog;
                    document.getElementById('catCount').textContent = data.cat;
                })
                .catch(error => console.error('Error fetching like counts:', error));
            }

            document.querySelectorAll('form').forEach(form => {
                form.addEventListener('submit', function(event) {
                    event.preventDefault();
                
                    const likeButton = this.querySelector('button');
                    likeButton.disabled = true;
                
                    const animal = this.querySelector('input[name="animal"]').value;
                    const formData = new URLSearchParams();
                    formData.append('animal', animal);
                
                    fetch('/api/like', {
                        method: 'POST',
                        body: formData,
                        headers: {
                            'Content-Type': 'application/x-www-form-urlencoded'
                        }
                    })
                    .then(response => {
                        if (!response.ok) {
                            throw new Error('Network response was not ok');
                        }
                        return response.json();
                    })
                    .then(data => {
                        console.log('Post response:', data);
                    })
                    .catch(error => {
                        console.error('Error submitting like:', error);
                        alert('An error occurred while submitting your like.');
                    })
                    .finally(() => {
                        likeButton.disabled = false;
                    });
                });
            });

            document.getElementById('resetButton').addEventListener('click', function() {
                fetch('/api/reset', {
                    method: 'DELETE'
                })
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }
                    return response.json();
                })
                .then(data => {
                    console.log('Reset response:', data);
                })
                .catch(error => console.error('Error resetting counts:', error));
            });

            updateLikeCounts();
        });
    </script>
</body>
</html>

`
